export const ACTION_TYPES = {
  SELECT_FROM_CURRENCY: 'SELECT_FROM_CURRENCY',
  SELECT_TO_CURRENCY: 'SELECT_TO_CURRENCY',
  SET_INPUT_VALUE: 'SET_INPUT_VALUE',
  SET_CURRENCIES: 'SET_CURRENCIES',
  SET_CONVERSION_RESULT: 'SET_CONVERSION_RESULT',
};
